name: test-pipeline

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: server

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: testing-action
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install npm for backend
        working-directory: server
        run: npm ci
      - name: install npm for frontend
        working-directory: client
        run: npm ci
      - name: backend lint
        working-directory: server
        run: npm run eslint
      - name: frontend lint
        working-directory: client
        run: npm run eslint
      - name: build frontend
        working-directory: client
        run: npm run build
      - name: test backend
        working-directory: server
        run: npm test
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          LOGIN_TOKENIZER: ${{ secrets.LOGIN_TOKENIZER }}
          GITHUB: true
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deployment job placeholder"