name: test-then-deploy-pipeline
# Linting and testing is automatic
# Daployment is triggered with "#deploy" in commit message 
# Version bumping is triggered with "#newvversion" in commit message 

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: server

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: testing-action
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install npm for backend
        working-directory: server
        run: npm ci
      - name: install npm for frontend
        working-directory: client
        run: npm ci
      - name: backend lint
        working-directory: server
        run: npm run eslint
      - name: frontend lint
        working-directory: client
        run: npm run eslint
      - name: build frontend
        working-directory: client
        run: npm run build
      - name: test backend
        working-directory: server
        run: npm test
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          LOGIN_TOKENIZER: ${{ secrets.LOGIN_TOKENIZER }}
          GITHUB: true

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install npm for backend
        working-directory: server
        run: npm ci
      - name: install npm for frontend
        working-directory: client
        run: npm ci
      - name: build frontend
        working-directory: client
        run: npm run build
      - name: delete front build from ignore
        working-directory: server
      - run: |
        echo "Editing .gitignore file"
        echo "node_modules" > .gitignore
      - uses: akhileshns/heroku-deploy@v3.8.9
        if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message), '#deploy') }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "blog-list-rv"
          heroku_email: "roman.m.vasilyev@gmail.com"
          appdir: "server"
          procfile: "web: npm start"
          healthcheck: "https://blog-list-rv.herokuapp.com/"
          rollbackonhealthcheckfailed: true

  new-version:
    needs: [build-and-test, deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push a tag
        uses: anothrNick/github-tag-action@1.26.0
        if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message), '#newversion') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

          node_modules
front_build

.env