name: test-pipeline

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - name: eslint
        run: npm run eslint
      - run: npm run build
      - run: npm test:back
      - run: npm test:front